# -*- Makefile -*-

# Copyright (C) Simon Wright <simon@pushface.org>

# This package is free software; you can redistribute it and/or
# modify it under terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2, or
# (at your option) any later version. This package is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License distributed with this package; see file COPYING.  If not,
# write to the Free Software Foundation, 59 Temple Place - Suite
# 330, Boston, MA 02111-1307, USA.

# This Makefile is used for distribution generation.

# DIST is the location where distribution files are to be copied, eg
# /Users/simon/coldframe/cf-20110731hg

include ../Makefile.inc

all:
	@echo "Only meant to be called from the parent Makefile.dist."

DATE = $(subst cf-,,$(notdir $(DIST)))

COMPILATION_REGRESSIONS +=								   \
  Compilation_Regressions.impl/compilation_regressions-aliased_components-check_access.adb \
  Compilation_Regressions.impl/compilation_regressions-subunits.adb			   \
  Compilation_Regressions.impl/compilation_regressions-subunits.ads

EVENT_TEST +=							\
  coldframe-events_test.adb					\
  coldframe-events_test_support.adb				\
  coldframe-events_test_support.ads				\
  Event_Test.gpr						\
  Event_Test.impl/event_test-completion_transitions-a1.adb	\
  Event_Test.impl/event_test-completion_transitions-a2.adb	\
  Event_Test.impl/event_test-completion_transitions-a3.adb	\
  Event_Test.impl/event_test-events-initialize.adb		\
  Event_Test.impl/event_test-machine-handle_mark.adb		\
  Event_Test.impl/event_test-machine-handle_self.adb		\
  Event_Test.impl/event_test-machine-send_done.adb		\
  Event_Test.impl/event_test-machine-set_timer.adb		\
  Event_Test.impl/event_test-recipient-handle_mark.adb		\
  Event_Test.impl/event_test-recipient-handle_self.adb		\
  Event_Test.impl/event_test-recipient-information_handler.adb	\
  Event_Test.impl/event_test-recipient-init.adb			\
  Event_Test.impl/event_test-recipient-send_done.adb		\
  Event_Test.impl/event_test-recipient-wait_handler.adb		\
  Event_Test.impl/event_test-timer_task_teardown-e1_handler.adb	\
  Event_Test.impl/event_test-timer_task_teardown-e2_handler.adb	\
  Event_Test.impl/event_test-timer_task_teardown-start.adb	\
  Event_Test.impl/event_test-timer_task_teardown-t.adb		\
  Event_Test.test/debugging.ads					\
  Event_Test.test/event_test-harness.adb			\
  Event_Test.test/event_test-harness.ads			\
  Event_Test.test/event_test-suite.adb				\
  Event_Test.test/event_test-suite.ads				\
  Event_Test.test/event_test-test_class.adb			\
  Event_Test.test/event_test-test_class.ads			\
  Event_Test.test/event_test-test_completion_transitions.adb	\
  Event_Test.test/event_test-test_completion_transitions.ads	\
  Event_Test.test/event_test-test_engine.adb			\
  Event_Test.test/event_test-test_engine.ads			\
  Event_Test.test/event_test-test_inspection.adb		\
  Event_Test.test/event_test-test_inspection.ads		\
  Event_Test.test/event_test-test_instance.adb			\
  Event_Test.test/event_test-test_instance.ads			\
  Event_Test.test/event_test-test_queue.adb			\
  Event_Test.test/event_test-test_queue.ads			\
  Event_Test.test/event_test-test_singleton_instance.adb	\
  Event_Test.test/event_test-test_singleton_instance.ads	\
  Event_Test.test/event_test-test_timer_task_teardown.adb	\
  Event_Test.test/event_test-test_timer_task_teardown.ads

HIERARCHIES +=						\
  Hierarchies.gpr					\
  Hierarchies.impl/hierarchies-f_2-create_new.adb	\
  Hierarchies.test/hierarchies-harness.adb		\
  Hierarchies.test/hierarchies-harness.ads		\
  Hierarchies.test/hierarchies-suite.adb		\
  Hierarchies.test/hierarchies-suite.ads		\
  Hierarchies.test/hierarchies-test_creations.adb	\
  Hierarchies.test/hierarchies-test_creations.ads	\
  Hierarchies.test/hierarchies-test_deletions.adb	\
  Hierarchies.test/hierarchies-test_deletions.ads	\
  Hierarchies.test/hierarchies-test_finds.adb		\
  Hierarchies.test/hierarchies-test_finds.ads

INITIALIZATION +=							   \
  Initialization.gpr							   \
  Initialization.impl/initialization-checking_domain_initialization-initialize.adb \
  Initialization.impl/initialization-checking_domain_initialization-t.adb  \
  Initialization.impl/initialization-harness.adb			   \
  Initialization.impl/initialization-harness.ads			   \
  Initialization.impl/initialization-suite.adb				   \
  Initialization.impl/initialization-suite.ads				   \
  Initialization.impl/initialization-suite-check_domain_initialization.adb

REGRESSIONS +=						\
  Regressions.gpr					\
  Regressions.test/association_classes-test.adb		\
  Regressions.test/association_classes-test.ads		\
  Regressions.test/associations-test.adb		\
  Regressions.test/associations-test.ads		\
  Regressions.test/regression_tests.adb			\
  Regressions.test/regressions_suite.adb		\
  Regressions.test/regressions_suite.ads		\
  Regressions.test/sf_2991721-test.adb			\
  Regressions.test/sf_2991721-test.ads			\
  Regressions.test/sf_3086637_suite.adb			\
  Regressions.test/sf_3086637_suite.ads

STUB_TEST +=					\
  Stub_Test.gpr					\
  Stub_Test.test/stub_test_harness.adb		\
  Stub_Test.test/stub_test_suite.adb		\
  Stub_Test.test/stub_test_suite.ads

UNIT_TESTING +=						\
  Unit_Testing.gpr					\
  Unit_Testing.impl/unit_testing-arr-post_c.adb		\
  Unit_Testing.impl/unit_testing-normal-post_c.adb	\
  Unit_Testing.impl/unit_testing-singleton-post_c.adb	\
  Unit_Testing.test/unit_testing-harness.adb		\
  Unit_Testing.test/unit_testing-suite.adb		\
  Unit_Testing.test/unit_testing-suite.ads

ALL = $(COMPILATION_REGRESSIONS) $(EVENT_TEST) $(HIERARCHIES)	\
  $(INITIALIZATION) $(REGRESSIONS) $(STUB_TEST) $(UNIT_TESTING)

ALL += Makefile

dist:
	-$(RM) -rf $(DIST)/test
	$(MKDIR) -p $(DIST)/test
	$(TAR) cf - $(ALL) | tar xf - -C $(DIST)/test/

.PHONY: dist force
