name = "library"
description = "Library demonstrator"
version = "71.0.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

executables = ["library"]

[gpr-set-externals]
COLDFRAME_PROFILE = "standard"
COLDFRAME_CONTAINERS = "standard"
COLDFRAME_BUILD = "Debug"
COLDFRAME_RUNTIME = "native"

[[actions]]
type = "pre-build"
command = ["make", "-C..", "Library.gen"]

[[depends-on]]
coldframe = "^71.0.0-dev"

[[pins]]
coldframe = { path='../..' }

[[depends-on]]
aunit = "^23.0.0"
