#!/bin/sh

#  Copyright (C) Simon Wright <simon@pushface.org>

#  This package is free software; you can redistribute it and/or
#  modify it under terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2, or
#  (at your option) any later version. This package is distributed in
#  the hope that it will be useful, but WITHOUT ANY WARRANTY; without
#  even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU General Public License for more
#  details. You should have received a copy of the GNU General Public
#  License distributed with this package; see file COPYING.  If not,
#  write to the Free Software Foundation, 59 Temple Place - Suite
#  330, Boston, MA 02111-1307, USA.

# $Id$

# This script creates the necessary build directories under the place
# specified by $BUILD_BASE.

[ -n "$BUILD_BASE" ] || (echo "BUILD_BASE not defined."; exit 1)

subdirs="aunit bc main patches"

for s in $subdirs; do
    d=$BUILD_BASE/$s
    [ -d $d ] || mkdir -p $d
done

#;; for emacs:
#;; Local Variables:
#;; mode: sh
#;; End:
