comp_opt=-gnatqQafoy -gnatwaL -O
bind_opt=-E
gnatmake_opt=-g -j2 -k -m
main=event_test-harness
main_unit=event_test-harness
build_dir=/home/simon/cf/.build/
check_cmd=${cross_prefix}gnatgcc -c ${comp_opt} ${full_current} -gnats
make_cmd=cd ${build_dir}
make_cmd=${cross_prefix}gnatmake -o ${main} ${main_unit} ${gnatmake_opt} -cargs ${comp_opt} -bargs ${bind_opt} -largs ${link_opt}
comp_cmd=cd ${build_dir}
comp_cmd=${cross_prefix}gnatgcc -c ${comp_opt} ${full_current}
run_cmd=cd ${build_dir}
run_cmd=${main}
src_dir=../Event_Test.test/
src_dir=../Event_Test.impl/
src_dir=../Event_Test.gen/
src_dir=../
src_dir=${HOME}/bc/
src_dir=/home/simon/aunit-1.01/aunit/framework/
src_dir=/home/simon/aunit-1.01/aunit/text_reporter/
obj_dir=./
debug_pre_cmd=cd ${build_dir}
debug_post_cmd=
