name = "van_fleet"
description = "Van Fleet demonstrator"
version = "71.0.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

executables = ["van_fleet"]

[gpr-set-externals]
COLDFRAME_PROFILE = "standard"
COLDFRAME_CONTAINERS = "standard"
COLDFRAME_BUILD = "Debug"
COLDFRAME_RUNTIME = "native"

[[depends-on]]
coldframe = "^71.0.0-dev"

[[pins]]
coldframe = { path='../..' }
