name = "stairwell_demo"
description = "Stairwell Lights demo"
version = "71.0.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

executables = ["stairwell_demo"]

[gpr-set-externals]
COLDFRAME_PROFILE = "standard"
COLDFRAME_CONTAINERS = "standard"
COLDFRAME_BUILD = "Debug"
COLDFRAME_RUNTIME = "native"

[[actions]]
type = "pre-build"
command = ["make",
           "-C..",
           "House_Management.gen",
           "Digital_IO.gen",
           "Digital_IO.Tcl.gen"]

[[depends-on]]
coldframe = "^71.0.0-dev"

[[pins]]
coldframe = { path='../..' }

[[depends-on]]
tash = "^8.7.0"
