# -*- Makefile -*-

# Copyright (C) Simon Wright <simon@pushface.org>

# This package is free software; you can redistribute it and/or
# modify it under terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2, or
# (at your option) any later version. This package is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License distributed with this package; see file COPYING.  If not,
# write to the Free Software Foundation, 59 Temple Place - Suite
# 330, Boston, MA 02111-1307, USA.

# This Makefile is used for distribution generation in the project/
# subdirectory.

# DIST is the location where distribution files are to be copied, eg
# /Users/simon/coldframe/cf-20110731hg

include ../Makefile.inc

all:
	@echo "Only meant to be called from the parent Makefile.dist."

COMMON =					\
coldframe-project.ads

STANDARD =							\
standard/coldframe-project-calendar.adb				\
standard/coldframe-project-calendar.ads				\
standard/coldframe-project-event_support.ads			\
standard/coldframe-project-events-callback_manager.ads		\
standard/coldframe-project-events-monitoring-test.ads		\
standard/coldframe-project-events-monitoring-test_trace.ads	\
standard/coldframe-project-events-monitoring-trace.ads		\
standard/coldframe-project-events-monitoring.ads		\
standard/coldframe-project-events-standard-inspection.ads	\
standard/coldframe-project-events-standard-test.ads		\
standard/coldframe-project-events-standard-test_debug.ads	\
standard/coldframe-project-events-standard-test_trace.ads	\
standard/coldframe-project-events-standard-trace.ads		\
standard/coldframe-project-events-standard.ads			\
standard/coldframe-project-events.ads				\
standard/coldframe-project-held_events-inspection.adb		\
standard/coldframe-project-held_events-inspection.ads		\
standard/coldframe-project-held_events-inspection_signature.ads	\
standard/coldframe-project-held_events-signature.ads		\
standard/coldframe-project-held_events.adb			\
standard/coldframe-project-held_events.ads			\
standard/coldframe-project-high_resolution_time.ads		\
standard/coldframe-project-limits.adb				\
standard/coldframe-project-limits.ads				\
standard/coldframe-project-log_error.adb			\
standard/coldframe-project-log_error.ads			\
standard/coldframe-project-log_info.adb				\
standard/coldframe-project-log_info.ads				\
standard/coldframe-project-logging_support.adb			\
standard/coldframe-project-logging_support.ads			\
standard/coldframe-project-times.adb				\
standard/coldframe-project-times.ads

RAVENSCAR =					\
ravenscar/coldframe-project-events.ads		\
ravenscar/coldframe-project-times.ads

ALL = $(COMMON) $(STANDARD) $(RAVENSCAR)

dist:
	-$(RM) -rf $(DIST)/project
	$(MKDIR) -p $(DIST)/project
	$(TAR) cf - $(ALL) | tar xf - -C $(DIST)/project/

.PHONY: dist force
