# -*- Makefile -*-

# Copyright (C) Simon Wright <simon@pushface.org>

# This package is free software; you can redistribute it and/or
# modify it under terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2, or
# (at your option) any later version. This package is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License distributed with this package; see file COPYING.  If not,
# write to the Free Software Foundation, 59 Temple Place - Suite
# 330, Boston, MA 02111-1307, USA.

# This Makefile is used for distribution generation in the lib/
# subdirectory.

# DIST is the location where distribution files are to be copied, eg
# /Users/simon/coldframe/cf-20110731hg

all::

include ../Makefile.inc
include Makefile.inc

COMMON =					\
coldframe-callbacks.ads				\
coldframe-exceptions.ads			\
coldframe-hash-access_hash.adb			\
coldframe-hash-access_hash.ads			\
coldframe-hash-instance_access_hash.ads		\
coldframe-hash-strings-standard.adb		\
coldframe-hash-strings-standard.ads		\
coldframe-hash-strings.ads			\
coldframe-hash.ads				\
coldframe-instances.ads				\
coldframe-memory_streams.adb			\
coldframe-memory_streams.ads			\
coldframe-time_signature.ads			\
coldframe.ads

STANDARD =									\
standard/coldframe-bounded_storage_pools.adb					\
standard/coldframe-bounded_storage_pools.ads					\
standard/coldframe-bounded_storage_pools.adb-sf3410667				\
standard/coldframe-bounded_storage_pools.ads-sf3410667				\
standard/coldframe-callbacks.adb						\
standard/coldframe-event_basis.adb						\
standard/coldframe-event_basis.ads						\
standard/coldframe-events_g-callback_manager_g.adb				\
standard/coldframe-events_g-callback_manager_g.ads				\
standard/coldframe-events_g-creation_g.adb					\
standard/coldframe-events_g-creation_g.ads					\
standard/coldframe-events_g-debug_g.adb						\
standard/coldframe-events_g-debug_g.ads						\
standard/coldframe-events_g-held_event_queue_signature-inspection_signature.ads	\
standard/coldframe-events_g-held_event_queue_signature.ads			\
standard/coldframe-events_g-monitoring_g.adb					\
standard/coldframe-events_g-monitoring_g.ads					\
standard/coldframe-events_g-standard_g-inspection_g.adb				\
standard/coldframe-events_g-standard_g-inspection_g.ads				\
standard/coldframe-events_g-standard_g.adb					\
standard/coldframe-events_g-standard_g.ads					\
standard/coldframe-events_g-test_g.adb						\
standard/coldframe-events_g-test_g.ads						\
standard/coldframe-events_g-trace_g.adb						\
standard/coldframe-events_g-trace_g.ads						\
standard/coldframe-events_g.adb							\
standard/coldframe-events_g.ads							\
standard/coldframe-exceptions-message.adb					\
standard/coldframe-exceptions-message.ads					\
standard/coldframe-exceptions-symbolic_traceback.adb				\
standard/coldframe-exceptions-symbolic_traceback.ads				\
standard/coldframe-exceptions-traceback.adb					\
standard/coldframe-exceptions-traceback.ads					\
standard/coldframe-hash-strings-bounded.adb					\
standard/coldframe-hash-strings-bounded.ads					\
standard/coldframe-hash-strings-unbounded.adb					\
standard/coldframe-hash-strings-unbounded.ads					\
standard/coldframe-interrupts.adb						\
standard/coldframe-interrupts.ads						\
standard/coldframe-simulation_time.adb						\
standard/coldframe-simulation_time.ads						\
standard/coldframe-smart_pointers.adb						\
standard/coldframe-smart_pointers.ads						\
standard/coldframe-stubs.adb							\
standard/coldframe-stubs.ads							\
standard/coldframe-synchronization.adb						\
standard/coldframe-synchronization.ads						\
standard/coldframe-task_deletion.adb						\
standard/coldframe-task_deletion.ads						\
standard/coldframe-task_deletion_g.adb						\
standard/coldframe-task_deletion_g.ads						\
standard/coldframe-unbounded_storage_pools.adb					\
standard/coldframe-unbounded_storage_pools.ads					\
standard/coldframe-unbounded_strings.adb					\
standard/coldframe-unbounded_strings.ads

RAVENSCAR =								\
ravenscar/coldframe-callbacks.adb					\
ravenscar/coldframe-events-callback_manager.adb				\
ravenscar/coldframe-events-callback_manager.ads				\
ravenscar/coldframe-events-standard-dispatchable_event_management.adb	\
ravenscar/coldframe-events-standard-held_event_management.adb		\
ravenscar/coldframe-events-standard.adb					\
ravenscar/coldframe-events-standard.ads					\
ravenscar/coldframe-events.adb						\
ravenscar/coldframe-events.ads						\
ravenscar/coldframe-times.ads

ALL = $(COMMON) $(STANDARD) $(RAVENSCAR)

ALL += default-uml14.xmi ColdFrameProfile.xmi Makefile

dist:
	-$(RM) -rf $(DIST)/lib
	$(MKDIR) -p $(DIST)/lib
	$(TAR) cf - $(ALL) | tar xf - -C $(DIST)/lib/
	$(CP) -p Makefile-for-distribution $(DIST)/lib/Makefile

.PHONY: all dist setup
