name = "performance"
description = "Performance demonstrator"
version = "71.0.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

executables = ["performance"]

[gpr-set-externals]
COLDFRAME_PROFILE = "standard"
COLDFRAME_CONTAINERS = "standard"
COLDFRAME_BUILD = "Debug"
COLDFRAME_RUNTIME = "native"

[[actions]]
type = "pre-build"
command = ["make", "-C..", "Performance.gen"]

[[depends-on]]
coldframe = "^71.0.0-dev"

[[pins]]
coldframe = { path='../..' }
