name = "arduino"
description = "Simple Buttons demonstrator on Arduino Due"
version = "71.0.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = "simple_buttons.gpr"

executables = ["simple_buttons"]

[environment]
TARGET.set = "arm-eabi"
PLATFORM_BUILD.set = "Production"
ADL_BUILD.set = "Production"
ADL_BUILD_CHECKS.set = "Disabled"

[gpr-set-externals]
COLDFRAME_PROFILE = "ravenscar"
COLDFRAME_CONTAINERS = "standard"
COLDFRAME_BUILD = "Debug"
COLDFRAME_RUNTIME = "/Users/simon/Developer/cortex-gnat-rts/local/arduino-due"

[[actions]]
type = "pre-build"
command = ["make", "Simple_Buttons.gen", "Digital_IO.gen"]

[[depends-on]]
coldframe = "*"

[[pins]]
coldframe = { path='../..' }

[[depends-on]]
gnat_external = ">=12.2.0"
