name = "house_management_test"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

executables = ["house_management_test"]

[[depends-on]]
coldframe = "^71.0.0-dev"

[[pins]]
coldframe = { path='../..' }

[[depends-on]]
aunit = "^23.0.0"
