#!/bin/sh

#  Copyright (C) Simon Wright <simon@pushface.org>

#  This package is free software; you can redistribute it and/or
#  modify it under terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2, or
#  (at your option) any later version. This package is distributed in
#  the hope that it will be useful, but WITHOUT ANY WARRANTY; without
#  even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU General Public License for more
#  details. You should have received a copy of the GNU General Public
#  License distributed with this package; see file COPYING.  If not,
#  write to the Free Software Foundation, 59 Temple Place - Suite
#  330, Boston, MA 02111-1307, USA.

# Installs ColdFrame's project source files in your directory.
# Suppose your overriding source is in ~/Base/Build/ColdFrameProject/project,
# change directory to ~/Base/Build/ColdFrameProject and say
#   $ $COLDFRAME/scripts/install-project
# This will place those of ColdFrame's files that you haven't overridden in
# ~/Base/Build/ColdFrameProject/inherited

rm -rf inherited
mkdir inherited
for f in $COLDFRAME/project/*.ad[bs]; do \
  [ -f project/`basename $f` ] || cp -p $f inherited/; \
done

#;; for emacs:
#;; Local Variables:
#;; mode: sh
#;; End:
