name = "stm32f4"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = "simple_buttons.gpr"

executables = ["simple_buttons"]

[environment]
TARGET.set = "arm-eabi"
#RTS.set = "embedded-stm32f4"
RTS.set = "stm32f4"
CONTAINERS.set = "minimal"
COLDFRAME_BUILD.set = "Production"
PLATFORM_BUILD.set = "Production"
ADL_BUILD.set = "Production"
ADL_BUILD_CHECKS.set = "Disabled"

[[actions]]
type = "pre-build"
command = ["make", "Simple_Buttons.gen", "Digital_IO.gen"]

[[actions]]
type = "post-build"
command = ["arm-eabi-objcopy",
           "-Obinary",
           "simple_buttons",
           "simple_buttons.bin"]

[[depends-on]]
coldframe = "*"

[[pins]]
coldframe = { path='../..' }

#[[depends-on]]
#gnat_arm_elf = "^12.2.1"
