name = "microbit"
description = "Simple Buttons demonstrator on BBC micro:bit (v1.3b)"
version = "71.0.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = "simple_buttons.gpr"

executables = ["simple_buttons"]

[environment]
TARGET.set = "arm-eabi"
PLATFORM_BUILD.set = "Production"
ADL_BUILD.set = "Production"
ADL_BUILD_CHECKS.set = "Disabled"

[gpr-set-externals]
COLDFRAME_PROFILE = "ravenscar"
COLDFRAME_CONTAINERS = "minimal"
COLDFRAME_BUILD = "Debug"
COLDFRAME_RUNTIME = "/Users/simon/Developer/cortex-gnat-rts/local/microbit"

[[actions]]
type = "pre-build"
command = ["make", "Simple_Buttons.gen", "Digital_IO.gen"]

[[actions]]
type = "post-build"
command = ["arm-eabi-objcopy",
           "-v",
           "-Oihex",
           "simple_buttons",
           "simple_buttons.hex"]

[[depends-on]]
coldframe = "*"

[[pins]]
coldframe = { path='../..' }

[[depends-on]]
gnat_external = ">=12.2.0"
