------------------------------------------------------------------------
--                                                                    --
--                     McKae Software Utilities                       --
--                                                                    --
--           Copyright (C) 2004 McKae Technologies                    --
--                                                                    --
-- The  McKae   software  utilities   are  free  software;   you  can --
-- redistribute it  and/or modify it  under terms of the  GNU General --
-- Public  License  as published  by  the  Free Software  Foundation; --
-- either version  2, or (at  your option) any later  version.  McKae --
-- Software Utilities are  distributed in the hope that  they will be --
-- useful,  but  WITHOUT  ANY  WARRANTY;  without  even  the  implied --
-- warranty of  MERCHANTABILITY or FITNESS FOR  A PARTICULAR PURPOSE. --
-- See the GNU  General Public License for more  details.  You should --
-- have received a copy of the GNU General Public License distributed --
-- with DTraq; see file COPYING.   If not, write to the Free Software --
-- Foundation, 59  Temple Place -  Suite 330, Boston,  MA 02111-1307, --
-- USA.                                                               --
--                                                                    --
-- As a  special exception, if other files  instantiate generics from --
-- this unit,  or you link this  unit with other files  to produce an --
-- executable,  this unit  does  not by  itself  cause the  resulting --
-- executable to be covered by  the GNU General Public License.  This --
-- exception does  not however invalidate  any other reasons  why the --
-- executable file might be covered by the GNU Public License.        --
--                                                                    --
-- The McKae Software Utilities  are maintained by McKae Technologies --
-- (http://www.mckae.com).                                            --
------------------------------------------------------------------------
-- A lexical scanner generated by aflex
------------------------------------------------------------------------
with text_io; use text_io;
with xia_parser_dfa; use xia_parser_dfa;
with xia_parser_io; use xia_parser_io;
--# line 1 "xia_parser.l"
-- Automatically generated AFLEX input
-- from AdaGOOP (by Martin C. Carlisle)
-- Do not modify.
--# line 14 "xia_parser.l"

package xia_parser is
   type Token is (
      End_Of_Input,
      Error,
      NCNAME_token,
      DECIMAL_LITERAL_token,
      INTEGER_token,
      DQ_LITERAL_token,
      SQ_LITERAL_token,
      LE_token,
      LT_token,
      GE_token,
      GT_token,
      NE_token,
      EQ_token,
      V_BAR_token,
      DOLLAR_token,
      COMMA_token,
      AT_SIGN_token,
      DOUBLE_COLON_token,
      COLON_token,
      DOUBLE_SLASH_token,
      SLASH_token,
      DOUBLE_DOT_token,
      DOT_token,
      MINUS_token,
      PLUS_token,
      STAR_token,
      R_BRACKET_token,
      L_BRACKET_token,
      R_PAREN_token,
      L_PAREN_token,
      OR_token,
      MOD_token,
      DIV_token,
      AND_token,
      NODE_token,
      PROCESSING_INSTRUCTION_token,
      TEXT_token,
      COMMENT_token,
      SELF_token,
      PRECEDING_SIBLING_token,
      PRECEDING_token,
      PARENT_token,
      NAMESPACE_token,
      FOLLOWING_SIBLING_token,
      FOLLOWING_token,
      DESCENDANT_OR_SELF_token,
      DESCENDANT_token,
      CHILD_token,
      ATTRIBUTE_token,
      ANCESTOR_OR_SELF_token,
      ANCESTOR_token,
      Dummy_Token);

   procedure Reset(Set_String : in String);
   function Get_Token return Token;
   function Get_Token_String return String;
   function Get_Current_Line return Natural;
   function Get_Current_Column return Natural;
   procedure Close_Files;
end xia_parser;
